add documentation URL to pyproject specifications
mxcube/mxcube3 pull request #1122
Opened 2023-11-01 10:34 UTC by elmjag

It seems that poetry started to insist that 'documentation' field must contain a valid URL. Poetry will refuse to install package with an empty 'documentation' field.

Let's point to our generated docs at readthedocs.io site.

2023-11-01 10:38 UTC, fabcor-maxiv requested changes

2023-11-01 10:38 UTC, fabcor-maxiv commented on pyproject.toml
> +documentation = "https://mxcubeweb.readthedocs.io/en/latest/"
I would remove the `en/latest/` suffix.

2023-11-01 10:45 UTC, fabcor-maxiv approved these changes

2023-11-02 07:20 UTC, marcus-oscarsson commented
Thanks !

2023-11-02 07:20 UTC, merged