Decouple fetching layer from Redux, part 4
mxcube/mxcube3 pull request #1131
Opened 2023-11-08 14:26 UTC by axelboc

Last two remaining endpoints of the Beamline API: `sendSetAttribute` and `sendExecuteCommand`.

I've also written a tiny bit of developer documentation as you suggested, @fabcor-maxiv. I hope the RST syntax is right, I'm not familiar with it... Would it be feasible to switch to Markdown? :sweat_smile:

2023-11-08 15:06 UTC, fabcor-maxiv commented
> I hope the RST syntax is right, I'm not familiar with it... Would it be feasible to switch to Markdown?

It supports both. It should work with any `.md` file. :)

https://www.sphinx-doc.org/en/master/usage/markdown.html

If not, let me know, I can probably help.

Preview: https://mxcubeweb--1131.org.readthedocs.build/en/1131/dev/front-end.html

Seems fine :)

2023-11-08 15:14 UTC, fabcor-maxiv requested changes, later dismissed

2023-11-08 15:14 UTC, fabcor-maxiv commented on docs/source/dev/front-end.rst
> +- Library `wretch <https://github.com/elbywan/wretch>`_ is used for making HTTP requests; it is a thin wrapper around the `Fetch API <https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API>`_.
Needs empty line between different nesting levels:
https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#lists-and-quote-like-blocks

```suggestion
- For each back-end API called by the front-end, there is a file under ``src/api/`` named after that API (e.g. ``beamline.js``, ``login.js`` ...)
- For each endpoint, there is a function in the API's front-end file dedicated to making HTTP requests to that endpoint (e.g. ``fetchLoginInfo``, ``sendRunBeamlineAction`` ...)

  - Functions that retrieve resources are named ``fetch<Something>``.
  - Functions that perform actions are named ``send<DoSomething>``.

- Library `wretch <https://github.com/elbywan/wretch>`_ is used for making HTTP requests; it is a thin wrapper around the `Fetch API <https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API>`_.
```

2023-11-08 15:31 UTC, axelboc commented on docs/source/dev/front-end.rst
> +- Library `wretch <https://github.com/elbywan/wretch>`_ is used for making HTTP requests; it is a thin wrapper around the `Fetch API <https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API>`_.
Oh great, well, if you don't mind, I've switched to Markdown :grin:

2023-11-08 15:31 UTC, axelboc commented on docs/source/dev/front-end.rst
> +- Library `wretch <https://github.com/elbywan/wretch>`_ is used for making HTTP requests; it is a thin wrapper around the `Fetch API <https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API>`_.
Love the deploy previews of the documentation site, by the way :trophy:

2023-11-08 15:35 UTC, axelboc commented
GitHub seems to consider canceled CI jobs as failed. Anyway to change that?

2023-11-08 15:44 UTC, fabcor-maxiv commented
> GitHub seems to consider canceled CI jobs as failed. Anyway to change that?

There is some kind of issue about actions workflow being triggered by both the `push` and the `pull request`. I will try to find a fix.

But anyway I do not think it is blocking the review. I had made a review "Changes requested" but then you moved from `.rst` to `.md` so the change is not necessary anymore. I have now dismissed this review that I had made.

2023-11-08 15:48 UTC, axelboc commented
> There is some kind of issue about actions workflow being triggered by both the `push` and the `pull request`. I will try to find a fix.

This is how I deal with this in the UI workflow: https://github.com/mxcube/mxcubeweb/blob/develop/.github/workflows/ui.yml#L11

2023-11-08 16:36 UTC, fabcor-maxiv commented
> > There is some kind of issue about actions workflow being triggered by both the `push` and the `pull request`. I will try to find a fix.
> 
> This is how I deal with this in the UI workflow: https://github.com/mxcube/mxcubeweb/blob/develop/.github/workflows/ui.yml#L11
> 
> Basically, the `pull_request` trigger is required only for PRs from forks for which the `push` trigger doesn't run, so I skip the `pull_request` trigger when it's not required (i.e. for local PRs)

As far as I understood this safeguard is not necessary if we keep our pull request branches on our own personal forks instead of on the upstream repository directly. This is a bit strange to me to push branches directly on the upstream repository on GitHub.

2023-11-08 16:51 UTC, fabcor-maxiv commented
Let's see if it happens again with this: https://github.com/mxcube/mxcubeweb/pull/1133

2023-11-09 07:15 UTC, marcus-oscarsson commented
@fabcor-maxiv #1133 seems to have done the trick

2023-11-09 07:15 UTC, merged

2023-11-09 08:10 UTC, axelboc commented
> As far as I understood this safeguard is not necessary if we keep our pull request branches on our own personal forks instead of on the upstream repository directly. This is a bit strange to me to push branches directly on the upstream repository on GitHub.

We are maintainers of the project with write access, so it feels natural to me. :thinking: The simplest process is often the best! :grin: Forks are typically more for external contributors, or when you want to start your own version of a project.

2023-11-09 09:20 UTC, fabcor-maxiv commented
>  #1133 seems to have done the trick

Great! :)

---

For the sake of the argument...

In my experience working with forks is more natural especially on forges like GitHub, GitLab, and so on. GitHub is built around this workflow with forks. For me working with the upstream directly is kind of like `sudo` mode. The other advantage of working with forks exclusively is that the upstream repository stays clean with typically only 2 branches `develop` and `main` (and sometimes some long-lived feature branches that need to be shared with all but it is rare).

But I don't mind much either way. In this case I can keep doing pull requests from my own fork.