Solving issues with shapes
mxcube/mxcube3 pull request #1223
Opened 2024-04-16 10:06 UTC by dominikatrojanowska

Solving issues:

* Unsaved Points
    Right click on a unsaved point gives the following error:
```
Uncaught runtime errors:
ERROR 
Cannot set properties of undefined (setting 'selected') TypeError: Cannot set properties of undefined (setting 'selected') at http://localhost:3000/static/js/bundle.js:28045:28 at Array.forEach () at SampleImage.clearSelection 
(...)
```

* 2D points
    If there is no sample added (manually mounted), and you right click on image and select "Data collecion (Limited OSC)" we get the error:
```
Uncaught runtime errors: 
ERROR
Cannot read properties of undefined (reading 'defaultPrefix') TypeError: Cannot read properties of undefined (reading 'defaultPrefix') at ContextMenu.showModal 
(...)
```

* Unclear how to trigger… But having a sample mounted, and you right click on image and select "Data collecion (Limited OSC)", once the 2D point is on screen, rigth click on it  we get the following errors (i am not sure why/how these two errors are different on the same scenario, probably the refresh does something)
```
Uncaught runtime errors:
ERROR
Cannot read properties of undefined (reading 'state') TypeError: Cannot read properties of undefined (reading 'state') at SampleImage.rightClick (http://localhost:3000/static/js/bundle.js:27796:78)
```
and 
```
Uncaught runtime errors:
ERROR
Cannot set properties of undefined (setting 'selected') TypeError: Cannot set properties of undefined (setting 'selected') at http://localhost:3000/static/js/bundle.js:28045:28 at Array.forEach (<anonymous>) at SampleImage.clearSelection (http://localhost:3000/static/js/bundle.js:28042:38) at SampleImage.selectShape (http://localhost:3000/static/js/bundle.js:27996:12) at http://localhost:3000/static/js/bundle.js:27832:16 at klass.forEachObject (http://localhost:3000/static/js/bundle.js:110530:16) at SampleImage.rightClick (http://localhost:3000/static/js/bundle.js:27829:19)
```

2024-04-16 11:03 UTC, fabcor-maxiv requested changes

2024-04-16 11:03 UTC, fabcor-maxiv commented on ui/package-lock.json
This might have been added my mistake. No?

2024-04-16 11:50 UTC, marcus-oscarsson commented
Thanks @dominikatrojanowska, I can't reproduce point 1 and 3 above. 

For point 2, there is a error because there is no sample added. The collection dialog will need some sample information so this solution will only allow for the dialog to be opened but the problem will remain (there is no sample added). In this case we should rather show the "no sample mounted" dialog, like is done for instance with 3-click centering.

2024-04-16 12:07 UTC, dominikatrojanowska commented on ui/package-lock.json
yes, thanks :)

2024-04-22 06:45 UTC, dominikatrojanowska commented
I was able to reproduce this case:
![2024-04-08 14_46_17-](https://github.com/mxcube/mxcubeweb/assets/154609837/99e60878-b337-46f4-98e8-b11bbf60083e)
but unfortunately, I didn't note the steps, just took the screenshot

2024-05-02 07:54 UTC, marcus-oscarsson commented
Hey @dominikatrojanowska  whats the status of this PR. Are you trying to solve the issue you posted above or is that something else you noticed while working on this ?

2024-05-06 08:16 UTC, dominikatrojanowska commented
Summarizing the current status of the task:

1. Unsaved Points - solved
2. 2D points - Data Collection etc. - I added the banner with appropriate information
![image](https://github.com/mxcube/mxcubeweb/assets/154609837/631638cc-8ace-4bba-b4c8-812c9065ed68)

4. "Unclear how to trigger… But having a sample mounted, and you right-click..." - I think is also solved 

what's next? should I rebase and merge it?

2024-05-06 13:39 UTC, fabcor-maxiv reviewed
Some linting issue: https://github.com/mxcube/mxcubeweb/actions/runs/8779685613/job/24632712967?pr=1223

2024-05-06 13:39 UTC, fabcor-maxiv commented on ui/src/components/SampleView/ContextMenu.js
> +      this.props.showErrorPanel(true, 'There is no sample mounted, cannot collect data.')
```suggestion
      this.props.showErrorPanel(true, 'There is no sample mounted, cannot collect data.')
```

2024-05-07 10:58 UTC, fabcor-maxiv approved these changes

2024-05-13 06:40 UTC, marcus-oscarsson commented
Thanks :)

2024-05-13 07:03 UTC, merged