Observers are not inControle so they cannot select proposal
mxcube/mxcube3 pull request #911
Opened 2022-02-23 12:42 UTC by meghdadyazdi

2022-02-25 12:32 UTC, meguiraun requested changes

2022-02-25 12:32 UTC, meguiraun commented on mxcube3/core/components/user/usermanager.py
> +                "islocal": "",
can we camelCasify this?

2022-02-25 12:32 UTC, meguiraun commented on mxcube3/ui/actions/login.js
> +              dispatch(selectProposal(resp.selectedProposal));
is this really needed? I would assume that in this case the proposal has already been selected by whoever is in control and loged in first.

Also, what happens if you refresh the page after you have selected a proposal? does the selection modal appears again? I am unsure if you would need to check if a proposal has been selected instead of checking if user is in control

2022-02-25 12:32 UTC, meguiraun commented on mxcube3/ui/components/RemoteAccess/ObserverDialog.jsx
> +  observerName() {
is looks as repeated code, can it be merged? You could use the same code and just disable the edtion of the name in case of user login

2022-02-28 10:05 UTC, meghdadyazdi commented on mxcube3/ui/actions/login.js
> +              dispatch(selectProposal(resp.selectedProposal));
If the user is not inControl then the user cannot select the proposal. The selected proposal is used for the user not inControl.

2022-03-18 09:32 UTC, marcus-oscarsson commented on mxcube3/ui/components/RemoteAccess/ObserverDialog.jsx
> +                      <Modal.Body>
Is this indentation right, looks a bit off ?

2022-03-18 09:33 UTC, marcus-oscarsson commented
Looks good in general. I guess this is not entirely done yet I'm thinking about the `local` role looks like it's never really added to the user ?

2022-09-15 17:13 UTC, closed without merging