early monkey patch
mxcube/mxcube3 pull request #960
Opened 2023-02-27 12:50 UTC by meguiraun

@marcus-oscarsson @rhfogh 

As discussed earlier, I am proposing this change since otherwise at MAX IV we have a recursion import problem with ssl context in one of our of our hwobjs.

Simply reordering the imports fixes our issue, but I am wondering if it breaks someone else's hwobj.

2023-02-28 12:25 UTC, rhfogh approved these changes
As it happened, I had already made this change (as a cleanup) in my local branch. I had just not pushed it. This is fine.`

2023-02-28 12:29 UTC, rhfogh requested changes
Your change is fine - but while you are at it, could you move the mxcube3 imports down below the python sys imports? This is nitpicking, but that is the accepted order.

2023-02-28 15:06 UTC, rhfogh approved these changes

2023-03-07 09:46 UTC, merged

2023-03-07 09:46 UTC, marcus-oscarsson commented
Well done guys :)